version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py